stages:
  - build
  - deploy


x64:
  stage: build
  image: lv2plugin/debian-x64
  script:
    - meson setup build/meson --prefix=$(pwd)/build/opt/ -Dbuildtype=release -Dtests=enabled -Dexess:docs=disabled -Dserd:docs=disabled -Dzix:docs=disabled -Dzix:tests_cpp=disabled -Dpython.platlibdir=$(pwd)/opt/lib/python/site-packages/ -Dpython.purelibdir=$(pwd)/opt/lib/python/site-packages/
    - meson install -C build/meson
    - PKG_CONFIG_PATH=build/opt/lib/pkgconfig CYTHONIZE=1 ./setup.py sdist
    - PKG_CONFIG_PATH=build/opt/lib/pkgconfig pyproject-build -n
    - PKG_CONFIG_PATH=build/opt/lib/pkgconfig LD_LIBRARY_PATH=build/opt/lib ./setup.py build
    - PKG_CONFIG_PATH=build/opt/lib/pkgconfig PYTHONPATH=build/opt/lib/python3.9/site-packages LD_LIBRARY_PATH=build/opt/lib ./setup.py test
    - PKG_CONFIG_PATH=build/opt/lib/pkgconfig PYTHONPATH=build/opt/lib/python3.9/site-packages LD_LIBRARY_PATH=build/opt/lib ./setup.py doctest
    - PKG_CONFIG_PATH=build/opt/lib/pkgconfig PYTHONPATH=build/opt/lib/python3.9/site-packages LD_LIBRARY_PATH=build/opt/lib sphinx-build -M epub doc build/doc/ -E -W -a -q
    - PKG_CONFIG_PATH=build/opt/lib/pkgconfig PYTHONPATH=build/opt/lib/python3.9/site-packages LD_LIBRARY_PATH=build/opt/lib sphinx-build -M html doc build/doc/ -E -W -a -q
    - PKG_CONFIG_PATH=build/opt/lib/pkgconfig PYTHONPATH=build/opt/lib/python3.9/site-packages LD_LIBRARY_PATH=build/opt/lib sphinx-build -M singlehtml doc build/doc/ -E -W -a -q
  artifacts:
    paths:
      - build/doc/epub/Using-Serd-in-Python.epub
      - build/doc/html
      - build/doc/singlehtml
      - dist/python-serd-1.0.1.tar.gz
      - dist/python_serd-1.0.1-cp39-cp39-linux_x86_64.whl


pages:
  stage: deploy
  script:
    - mkdir -p .public
    - mv build/doc/html/ .public/
    - mv build/doc/singlehtml/ .public/
    - mv build/sphinx/epub/Using-Serd-in-Python.epub .public/
    - mv .public public
  needs:
    - x64
  artifacts:
    paths:
      - public
  only:
    - main
